spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/users?authSource=admin
      database: users
      host: localhost
      port: 27017
      username: admin
      password: admin
